
---
    - name: Install go
       apt: name=golang-go state=present

    - name: Create dir for goapp and maingo bin
      file: path=/srv/sum/ state=directory

    - name: Clone main.go from github
      git:  repo=github.com/gro3a/sum dest=/srv/sum/

    - name:  Build goapp
      shell: go build /srv/goapp/main.go
      
    - name: Create systemd goapp.service
      template: src=systemd.maingo.service.conf.j2 dest=/etc/systemd/system/goapp.service

    - name: Start goapp.service
      shell: systemctl start goapp.service
        

