
---
    - name: install letsencrypt
      apt: name=letsencrypt state=latest

    - name: Create letsencrypt certificate
      shell: letsencrypt certonly -a -n  webroot --webroot-path=/var/www/html -m {{ letsencrypt_email }} -d {{ domain_name }}
      args:
        creates: /etc/letsencrypt/live/{{ domain_name }}
    
    - name: Add letsencrypt cronjob for cert renewal
      cron:
        name: letsencrypt_renewal
        special_time: daily
        job: letsencrypt --renew certonly -a webroot --webroot-path=/var/www/html && service nginx reload
